stages:
  - test
  - build
  - deploy


variables:
  ANDROID_HOME: "/Users/$USER/Library/Android/sdk"
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  PATH: "$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"


cache:
  key: ${CI_PROJECT_ID}
  paths:
    - vendor/bundle
    - .gradle/
    - build/
    - app/build/

before_script:
  - export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - ruby -v
  - gem install bundler:2.5.23 || gem install bundler -v "~> 2.3.0"
  - bundle install --path=vendor/bundle
  - bundle install

test:
  stage: test
  script:
    - bundle exec fastlane test
    - bundle exec fastlane lint
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

build_debug:
  stage: build
  script:
    - bundle exec fastlane build_debug
  only:
    - develop
  artifacts:
    paths:
      - app/build/outputs/apk/debug/

build_release:
  stage: build
  script:
    - echo "$ENCODED_KEYSTORE" | base64 -d > app/keystore.jks
    - export KEYSTORE_PATH="$PWD/app/keystore.jks"
    - bundle exec fastlane build_release
  only:
    - master
  artifacts:
    paths:
      - app/build/outputs/apk/release/

deploy_internal:
  stage: deploy
  script:
    - echo "$PLAY_STORE_JSON_KEY" > play-store-credentials.json
    - bundle exec fastlane deploy_internal
  only:
    - master
  when: manual