stages:
  - test
  - build

variables:
  JAVA_HOME: "/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home"
  ANDROID_HOME: "/Users/$USER/Library/Android/sdk"  # Default MacOS Android SDK location
  PATH: "$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$JAVA_HOME/bin:$PATH"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

test:
  stage: test
  before_script:
    - export ANDROID_HOME="/Users/$USER/Library/Android/sdk"
    - export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$JAVA_HOME/bin:$PATH"
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - chmod +x ./gradlew
    - java -version  # Verify Java version

  script:
    - ./gradlew test

  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

build:
  stage: build
  before_script:
    - export ANDROID_HOME="/Users/$USER/Library/Android/sdk"
    - export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$JAVA_HOME/bin:$PATH"
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - chmod +x ./gradlew
    - java -version

  script:
    - echo "$ENCODED_KEYSTORE" | base64 -d > app/keystore.jks
    - export KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
    - export KEY_ALIAS=$KEY_ALIAS
    - export KEY_PASSWORD=$KEY_PASSWORD
    - ./gradlew build

  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

  variables:
    GIT_DEPTH: 1