image: theimpulson/gitlab-ci-android

stages:
  - test
  - build

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

test:
  stage: test

  before_script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./gradlew
    - java -version  # Verify Java version

  script:
    - ./gradlew test

  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

build:
  stage: build

  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./gradlew
    - java -version

  script:
    - echo "$ENCODED_KEYSTORE" | base64 -d > app/keystore.jks
    - export KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
    - export KEY_ALIAS=$KEY_ALIAS
    - export KEY_PASSWORD=$KEY_PASSWORD
    - ./gradlew build

  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

  variables:
    GIT_DEPTH: 1