stages:
  - test
  - build
  - deploy

variables:
  ANDROID_HOME: "/Users/$USER/Library/Android/sdk"
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$JAVA_HOME/bin:$PATH"
  - bundle install

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - vendor/bundle
    - .gradle/
    - build/
    - app/build/

test:
  stage: test
  script:
    - bundle exec fastlane test
    - bundle exec fastlane lint
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

build_debug:
  stage: build
  script:
    - bundle exec fastlane build_debug
  only:
    - develop
  artifacts:
    paths:
      - app/build/outputs/apk/debug/

build_release:
  stage: build
  script:
    - echo "$ENCODED_KEYSTORE" | base64 -d > app/keystore.jks
    - export KEYSTORE_PATH="$PWD/app/keystore.jks"
    - bundle exec fastlane build_release
  only:
    - master
  artifacts:
    paths:
      - app/build/outputs/apk/release/

deploy_internal:
  stage: deploy
  script:
    - echo "$PLAY_STORE_JSON_KEY" > play-store-credentials.json
    - bundle exec fastlane deploy_internal
  only:
    - master
  when: manual